language: go
go:
  - 1.9.7
  - 1.10.4
  - "1.11"
install:
  - go get
services:
  - mysql
notifications:
  email: false
env:
  - MYSQL_CONNECTION='travis@tcp(127.0.0.1:3306)/test'
before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "source test/seed_data.sql;" -uroot test
script: go test -v -tags=mysql
