language: go
go:
  - 1.6.4
  - 1.7.1
  - 1.7.4
install:
  - go get
services:
  - mysql
notifications:
  email: false
env:
  - MYSQL_CONNECTION='travis@tcp(127.0.0.1:3306)/test'
before_script:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "source test/seed_data.sql;" -uroot test
  - go get github.com/stretchr/testify/assert
script: go test -tags=mysql
